CLASSES = {'pascal':    ['background', 'aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 
                      'car', 'cat', 'chair', 'cow', 'dining table', 'dog', 'horse', 'motorbike', 
                      'person', 'potted plant', 'sheep', 'sofa', 'train', 'tv/monitor'],
           'cityscapes':['road', 'sidewalk', 'building', 'wall', 'fence', 
                        'pole', 'traffic light', 'traffic sign', 'vegetation', 'terrain', 
                        'sky', 'person', 'rider', 'car', 'truck', 
                        'bus', 'train', 'motorcycle', 'bicycle'],
           'acdc':      ['road', 'sidewalk', 'building', 'wall', 'fence', 
                        'pole', 'traffic light', 'traffic sign', 'vegetation', 'terrain', 
                        'sky', 'person', 'rider', 'car', 'truck', 
                        'bus', 'train', 'motorcycle', 'bicycle'],
           'syn_city':  ['road', 'sidewalk', 'building', 'wall', 'fence', 
                        'pole', 'traffic light', 'traffic sign', 'vegetation', 'sky', 
                        'person', 'rider', 'car', 'bus', 'motorcycle', 
                        'bicycle'],
           'surround_school': ['road', 'sidewalk', 'building', 'guard rail', 
                               'pole', 'light', 'sign', 'tree', 
                               'terrain', 'sky', 'person', 'rider', 
                               'car', 'truck', 'bus', 'motocycle', 'bicycle'],
           'kyxz': ['backgounrd', 'drivable', 'dangerous', 'positive', 'negative', 'water'],
           'rellis3d': ['dirt', 'grass', 'tree', 'pole', 'water', 'sky', 'vehicle', 'object', 'asphalt', 'building', 'log', 'person', 'fence', 'bush', 'concrete', 'barrier', 'puddle', 'mud', 'rubble'],
           'parking_fisheye': ['background', 'parking line', 'white line', 'yellow line', 'zebra crossing', 'arrow', 'slope', 'other'],
           'bev_2023': ['background', 'parking line', 'white line', 'yellow line', 'zebra crossing', 'arrow', 'slope'],
           'bev_2024': ['background', 'parking line', 'white line', 'yellow line', 'zebra crossing', 'arrow', 'slope'],
           'bev_20234': ['background', 'parking line', 'white line', 'yellow line', 'zebra crossing', 'arrow', 'slope'],
           'bev_20234_6cls': ['background', 'white line', 'yellow line', 'zebra crossing', 'arrow', 'slope'],
           'avm_seg': ['background', 'free space', 'marker', 'vehicle', 'other objects'],
           'HYRoad': ['road', 'sidewalk', 'building', 'pole', 'traffic light', 'traffic sign', 'vegetation', 'trunk', 'terrain', 'sky', 'person', 'car', 'bicycle', 'static', 'background'],
           'HYRoad_3cls': ['background', 'pole', 'trunk'],
           'coco':      ['void', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 
                        'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 
                        'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra',
                        'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 
                        'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard',
                        'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon',
                        'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 
                        'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 
                        'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave',
                        'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 
                        'teddy bear', 'hair drier', 'toothbrush', 'banner', 'blanket', 'branch', 'bridge', 
                        'building-other', 'bush', 'cabinet', 'cage', 'cardboard', 'carpet', 'ceiling-other', 
                        'ceiling-tile', 'cloth', 'clothes', 'clouds', 'counter', 'cupboard', 'curtain',
                        'desk-stuff', 'dirt', 'door-stuff', 'fence', 'floor-marble', 'floor-other', 'floor-stone', 
                        'floor-tile', 'floor-wood', 'flower', 'fog', 'food-other', 'fruit', 'furniture-other', 
                        'grass', 'gravel', 'ground-other', 'hill', 'house', 'leaves', 'light', 'mat', 'metal', 
                        'mirror-stuff', 'moss', 'mountain', 'mud', 'napkin', 'net', 'paper', 'pavement', 'pillow', 
                        'plant-other', 'plastic', 'platform', 'playingfield', 'railing', 'railroad', 'river', 
                        'road', 'rock', 'roof', 'rug', 'salad', 'sand', 'sea', 'shelf', 'sky-other', 'skyscraper',
                        'snow', 'solid-other', 'stairs', 'stone', 'straw', 'structural-other', 'table', 'tent',
                        'textile-other', 'towel', 'tree', 'vegetable', 'wall-brick', 'wall-concrete', 'wall-other', 
                        'wall-panel', 'wall-stone', 'wall-tile', 'wall-wood', 'water-other', 'waterdrops',
                        'window-blind', 'window-other', 'wood'],
           'gtav_ist':  ['road', 'sidewalk', 'building', 'wall', 'fence', 
                        'pole', 'traffic light', 'traffic sign', 'vegetation', 'terrain', 
                        'sky', 'person', 'rider', 'car', 'truck', 
                        'bus', 'train', 'motorcycle', 'bicycle'],
           'gtav':      ['road', 'sidewalk', 'building', 'wall', 'fence', 
                        'pole', 'traffic light', 'traffic sign', 'vegetation', 'terrain', 
                        'sky', 'person', 'rider', 'car', 'truck', 
                        'bus', 'train', 'motorcycle', 'bicycle'],
           'syn':       ['road', 'sidewalk', 'building', 'wall', 'fence', 
                        'pole', 'traffic light', 'traffic sign', 'vegetation', 'sky', 
                        'person', 'rider', 'car', 'bus', 'motorcycle', 
                        'bicycle'],
           'syn_ist':   ['road', 'sidewalk', 'building', 'wall', 'fence', 
                        'pole', 'traffic light', 'traffic sign', 'vegetation', 'sky', 
                        'person', 'rider', 'car', 'bus', 'motorcycle', 
                        'bicycle'],
           }