# arguments for dataset
dataset: cityscapes
nclass: 19
resize_ratio: 1.0
crop_size: [640, 640]  # 1024
n_sample: 2975
workers: 4
data_root: data/cityscapes
data_list: splits/cityscapes/2975/labeled.txt

source:
  use_source: False
  type: gtav  # gtav_ist
  data_root: data/gtav
  data_list: data/train_list/gtav_train_list.txt

# arguments for training
epochs: 200
eval_interval: 5
batch_size: 2 # per GPU x 2 GPUs
n_gpus: 2
criterion:
  name: OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
optim:
  type: SGD
  times: 10
  kwargs:
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0001
lr_scheduler:
  mode: poly
  warmup: True
  warmup_iters: 1000
  warmup_mode: linear
  warmup_ratio: 0.0005
  kwargs:
    power: 0.9
conf_thresh: 0

# arguments for model
backbone: resnet18
