# arguments for dataset
dataset: bev_2024
nclass: 7
resize_ratio: 1.0
crop_size: [800, 800]  # 1024  960*1280, 480*640  [800, 1120]
n_sample: 140
workers: 4
data_root: data/bev_2024
data_list: data/train_list/bev_2024_train_list.txt

source:
  use_source: False
  type: bev_2023
  data_root: data/bev_2023
  data_list: data/train_list/bev_2023_train_list.txt

val:
  dataset: bev_2024
  data_root: data/bev_2024

# arguments for training
epochs: 100
batch_size: 2 # per GPU x 4 GPUs
n_gpus: 2
criterion:
  name: OHEM  # OHEM
  kwargs:
    ignore_index: 255
    thresh: 0.7
    min_kept: 200000
optim:
  type: SGD
  times: 10
  kwargs:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
lr_scheduler:
  mode: poly
  warmup: True
  warmup_iters: 1000
  warmup_mode: linear
  warmup_ratio: 0.0005
  kwargs:
    power: 0.9
conf_thresh: 0

# arguments for model
backbone: resnet18
